Training day and night
Namespace(lr=0.003)
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ./.pytorch/MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz



















































































































































99.5%
Extracting ./.pytorch/MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz to ./.pytorch/MNIST_data/MNIST/raw

28.4%%
Extracting ./.pytorch/MNIST_data/MNIST/raw/train-labels-idx1-ubyte.gz to ./.pytorch/MNIST_data/MNIST/raw























98.9%%
Extracting ./.pytorch/MNIST_data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./.pytorch/MNIST_data/MNIST/raw
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to ./.pytorch/MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz
Extracting ./.pytorch/MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./.pytorch/MNIST_data/MNIST/raw
Processing...
Done!
180.4%/opt/miniconda3/envs/MLOps/lib/python3.9/site-packages/torchvision/datasets/mnist.py:480: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /tmp/pip-req-build-x1rp5px8/torch/csrc/utils/tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
Traceback (most recent call last):
  File "/Users/carolinesofieljorring/Documents/MLOps/MLOps_github/main.py", line 147, in <module>
    TrainOREvaluate()
  File "/Users/carolinesofieljorring/Documents/MLOps/MLOps_github/main.py", line 31, in __init__
    getattr(self, args.command)()
  File "/Users/carolinesofieljorring/Documents/MLOps/MLOps_github/main.py", line 66, in train
    wandb.log('Loss: ', np.mean(train_losses))
  File "/opt/miniconda3/envs/MLOps/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1065, in log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary